//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGradMSVSExtention.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelFolder {
            get {
                return ((string)(this["ModelFolder"]));
            }
            set {
                this["ModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewFolder {
            get {
                return ((string)(this["ViewFolder"]));
            }
            set {
                this["ViewFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewModelFolder {
            get {
                return ((string)(this["ViewModelFolder"]));
            }
            set {
                this["ViewModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using System.Diagnostics;\r\n\r\nusing DatumNode.Models;\r\nusing System.ComponentModel" +
            ".DataAnnotations;\r\n\r\nnamespace %namespace%\r\n{\r\n    public class %classname%: Ent" +
            "ity\r\n    {\r\n    }\r\n}")]
        public string DefaultModel {
            get {
                return ((string)(this["DefaultModel"]));
            }
            set {
                this["DefaultModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public class %classname%\r\n    {\r\n    \tpublic %class" +
            "name%()\r\n    \t{\r\n    \t\t//InitializeComponent();\r\n    \t}\r\n    }\r\n}")]
        public string DefaultView {
            get {
                return ((string)(this["DefaultView"]));
            }
            set {
                this["DefaultView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using DatumNode.ViewModels;

using %prefix%ViewModels;
using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;

namespace %namespace%
{
    class %classname%sViewModel : ItemsViewModel<%classname%, %classname%Filter>
    {
        public %classname%sViewModel() : this(CommonMainViewModel.Resolve<I%classname%Repository>())
        {

        }

        public %classname%sViewModel(IRepository<%classname%, %classname%Filter> repository) : base(repository)
        {

        }

    }
}")]
        public string DefaultViewModel {
            get {
                return ((string)(this["DefaultViewModel"]));
            }
            set {
                this["DefaultViewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using DatumNode.ViewModels;

using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;

namespace %namespace%
{
	public class %classname%DetailViewModel : WorkspaceViewModel
	{

		 public %classname%DetailViewModel()
		 {

		 }

	}
}")]
        public string DefaultDetailViewModel {
            get {
                return ((string)(this["DefaultDetailViewModel"]));
            }
            set {
                this["DefaultDetailViewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using DatumNode.ViewModels;

using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;

namespace %namespace%
{
	class %classname%sMasterViewModel : MasterDetailViewModel<%classname%sViewModel, %classname%DetailViewModel>
	{
	  
	}
}")]
        public string DefaultMasterViewModel {
            get {
                return ((string)(this["DefaultMasterViewModel"]));
            }
            set {
                this["DefaultMasterViewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatumNodeRepositoryFolder {
            get {
                return ((string)(this["DatumNodeRepositoryFolder"]));
            }
            set {
                this["DatumNodeRepositoryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepositoryFolder {
            get {
                return ((string)(this["RepositoryFolder"]));
            }
            set {
                this["RepositoryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using System;
using System.Collections.Generic;

using DatumNode.ViewModels;

using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;

namespace %namespace%
{
	class %classname%sViewModel : ItemsView%classname%<%classname%, %classname%Filter>
	{
		 public %classname%sViewModel() : this(CommonMainViewModel.Resolve<I%classname%Repository>())
		 {

		 }
	}
}")]
        public string DefaultDatumNodeRepository {
            get {
                return ((string)(this["DefaultDatumNodeRepository"]));
            }
            set {
                this["DefaultDatumNodeRepository"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using DatumNode.ViewModels;\r\n\r\nusing %prefix%Models.%classname%s;\r\n\r\nnamespace %n" +
            "amespace%\r\n{\r\n\tpublic interface I%classname%Repository: IRepository<%classname%," +
            " %classname%Filter>\r\n\t{\r\n\r\n\t}\r\n}")]
        public string DefaultRepository {
            get {
                return ((string)(this["DefaultRepository"]));
            }
            set {
                this["DefaultRepository"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using System.Diagnostics;\r\n\r\nusing DatumNode.Models;\r\nusing System.ComponentModel" +
            ".DataAnnotations;\r\n\r\nnamespace %namespace%\r\n{\r\n    public class %classname%Filte" +
            "r: Entity\r\n    {\r\n    }\r\n}")]
        public string DefaultModelFilter {
            get {
                return ((string)(this["DefaultModelFilter"]));
            }
            set {
                this["DefaultModelFilter"] = value;
            }
        }
    }
}
