//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGradMSVSExtention.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelFolder {
            get {
                return ((string)(this["ModelFolder"]));
            }
            set {
                this["ModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewFolder {
            get {
                return ((string)(this["ViewFolder"]));
            }
            set {
                this["ViewFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewModelFolder {
            get {
                return ((string)(this["ViewModelFolder"]));
            }
            set {
                this["ViewModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public class %classname%\r\n    {\r\n    }\r\n}")]
        public string DefaultModel {
            get {
                return ((string)(this["DefaultModel"]));
            }
            set {
                this["DefaultModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public class %classname%\r\n    {\r\n    \tpublic %class" +
            "name%()\r\n    \t{\r\n    \t\tInitializeComponent();\r\n    \t}\r\n    }\r\n}")]
        public string DefaultView {
            get {
                return ((string)(this["DefaultView"]));
            }
            set {
                this["DefaultView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public class %classname%\r\n    {\r\n    }\r\n}")]
        public string DefaultViewModel {
            get {
                return ((string)(this["DefaultViewModel"]));
            }
            set {
                this["DefaultViewModel"] = value;
            }
        }
    }
}
