//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGradMSVSExtension.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelFolder {
            get {
                return ((string)(this["ModelFolder"]));
            }
            set {
                this["ModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewFolder {
            get {
                return ((string)(this["ViewFolder"]));
            }
            set {
                this["ViewFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewModelFolder {
            get {
                return ((string)(this["ViewModelFolder"]));
            }
            set {
                this["ViewModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using System.Diagnostics;\r\n\r\nusing DatumNode.Models;\r\nusing System.ComponentModel" +
            ".DataAnnotations;\r\n\r\nnamespace %namespace%\r\n{\r\n    public class %classname%: Ent" +
            "ity\r\n    {\r\n    }\r\n}")]
        public string DefaultModel {
            get {
                return ((string)(this["DefaultModel"]));
            }
            set {
                this["DefaultModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public partial class %classname%View\r\n    {\r\n    \tp" +
            "ublic %classname%View()\r\n    \t{\r\n    \t\tInitializeComponent();\r\n    \t}\r\n    }\r\n}")]
        public string DefaultView {
            get {
                return ((string)(this["DefaultView"]));
            }
            set {
                this["DefaultView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using DatumNode.ViewModels;

using %prefix%ViewModels;
using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;
using Oss.ViewModels;

namespace %namespace%
{
    class %classname%sViewModel : ItemsViewModel<%classname%, %classname%Filter>
    {
        public %classname%sViewModel() : this(CommonMainViewModel.Resolve<I%classname%Repository>())
        {

        }

        public %classname%sViewModel(IRepository<%classname%, %classname%Filter> repository) : base(repository)
        {

        }

    }
}")]
        public string DefaultViewModel {
            get {
                return ((string)(this["DefaultViewModel"]));
            }
            set {
                this["DefaultViewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using DatumNode.ViewModels;

using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;

namespace %namespace%
{
	public class %classname%DetailViewModel : WorkspaceViewModel
	{

		 public %classname%DetailViewModel()
		 {

		 }

	}
}")]
        public string DefaultDetailViewModel {
            get {
                return ((string)(this["DefaultDetailViewModel"]));
            }
            set {
                this["DefaultDetailViewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using DatumNode.ViewModels;

using %prefix%Models.%classname%s;
using %prefix%Repository.%classname%s;

namespace %namespace%
{
	class %classname%sMasterViewModel : MasterDetailViewModel<%classname%sViewModel, %classname%DetailViewModel>
	{
	  
	}
}")]
        public string DefaultMasterViewModel {
            get {
                return ((string)(this["DefaultMasterViewModel"]));
            }
            set {
                this["DefaultMasterViewModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatumNodeRepositoryFolder {
            get {
                return ((string)(this["DatumNodeRepositoryFolder"]));
            }
            set {
                this["DatumNodeRepositoryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RepositoryFolder {
            get {
                return ((string)(this["RepositoryFolder"]));
            }
            set {
                this["RepositoryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using DatumNode.ViewModels;\r\n\r\nusing %prefix%Models.%classname%s;\r\nusing %prefix%" +
            "Repository.%classname%s;\r\n\r\nnamespace %namespace%\r\n{\r\n\tclass %classname%Reposito" +
            "ry : Repository <%classname%, %classname%Filter>, I%classname%Repository\r\n\t{\r\n\t}" +
            "\t\r\n}")]
        public string DefaultDatumNodeRepository {
            get {
                return ((string)(this["DefaultDatumNodeRepository"]));
            }
            set {
                this["DefaultDatumNodeRepository"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using DatumNode.ViewModels;\r\n\r\nusing %prefix%Models.%classname%s;\r\n\r\nnamespace %n" +
            "amespace%\r\n{\r\n\tpublic interface I%classname%Repository: IRepository<%classname%," +
            " %classname%Filter>\r\n\t{\r\n\r\n\t}\r\n}")]
        public string DefaultRepository {
            get {
                return ((string)(this["DefaultRepository"]));
            }
            set {
                this["DefaultRepository"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("using System.Diagnostics;\r\n\r\nusing DatumNode.Models;\r\nusing System.ComponentModel" +
            ".DataAnnotations;\r\n\r\nnamespace %namespace%\r\n{\r\n    public class %classname%Filte" +
            "r: Entity\r\n    {\r\n    }\r\n}")]
        public string DefaultModelFilter {
            get {
                return ((string)(this["DefaultModelFilter"]));
            }
            set {
                this["DefaultModelFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<views:UserView x:Class=\"%namespace%.%classname%View\"\r\n    xmlns=\"http://schemas." +
            "microsoft.com/winfx/2006/xaml/presentation\"\r\n    xmlns:x=\"http://schemas.microso" +
            "ft.com/winfx/2006/xaml\"\r\n    xmlns:d=\"http://schemas.microsoft.com/expression/bl" +
            "end/2008\"\r\n    xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/" +
            "2006\" \r\n    xmlns:views=\"clr-namespace:DatumNode.Views;assembly=DatumNode.Contro" +
            "ls\" \r\n    xmlns:controls=\"clr-namespace:System.Windows.Controls;assembly=DatumNo" +
            "de.Controls\" \r\n    xmlns:controls1=\"clr-namespace:Oss.Controls\" \r\n    xmlns:wind" +
            "ows=\"clr-namespace:System.Windows;assembly=DatumNode.Controls\" \r\n    mc:Ignorabl" +
            "e=\"d\"\r\n    d:DesignHeight=\"300\" d:DesignWidth=\"600\">\r\n    <Grid x:Name=\"LayoutRo" +
            "ot\" Background=\"White\">\r\n        <Grid.RowDefinitions>\r\n            <RowDefiniti" +
            "on Height=\"auto\"/>\r\n            <RowDefinition/>\r\n        </Grid.RowDefinitions>" +
            "\r\n        <StackPanel Orientation=\"Horizontal\">\r\n            <TextBlock Margin=\"" +
            "3\" VerticalAlignment=\"Center\" Text=\"Фильтр\"/>\r\n            <TextBox Width=\"100\" " +
            "Margin=\"0,3,3,3\" Text=\"{Binding Path=FilterText, Mode=TwoWay}\" windows:BindingHe" +
            "lper.UpdateSourceOnChange=\"True\"/>\r\n            <controls:CustomDatePicker Margi" +
            "n=\"3\" SelectedDate=\"{Binding Path=Filter.Date, Mode=TwoWay}\" windows:BindingHelp" +
            "er.UpdateSourceOnChange=\"True\"/>\r\n            <CheckBox Margin=\"3\" VerticalAlign" +
            "ment=\"Center\" IsChecked=\"{Binding Path=Filter.IsClosed, Mode=TwoWay}\" Content=\"З" +
            "акрытые\" windows:BindingHelper.UpdateSourceOnChange=\"True\"/>\r\n            <contr" +
            "ols1:Toolbar ShowDeleteDialog=\"True\"/>\r\n        </StackPanel>\r\n        <controls" +
            ":CustomDataGrid Grid.Row=\"1\" IsReadOnly=\"True\" MaxColumnAutoWidth=\"9999\" AutoGen" +
            "erateColumns=\"True\" ItemsSource=\"{Binding Path=ItemsView}\" SelectedItem=\"{Bindin" +
            "g Path=CurrentItem, Mode=TwoWay}\" SelectionMode=\"Single\"/>\r\n    </Grid>\r\n</views" +
            ":UserView>")]
        public string DefaultViewXaml {
            get {
                return ((string)(this["DefaultViewXaml"]));
            }
            set {
                this["DefaultViewXaml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<views:UserView x:Class=""%namespace%.%classname%DetailView""
    xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""
    xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml""
    xmlns:d=""http://schemas.microsoft.com/expression/blend/2008""
    xmlns:mc=""http://schemas.openxmlformats.org/markup-compatibility/2006""
    xmlns:views=""clr-namespace:DatumNode.Views;assembly=DatumNode.Controls""
    xmlns:controls=""clr-namespace:DatumNode.Controls;assembly=DatumNode.Controls""
    xmlns:sdk=""http://schemas.microsoft.com/winfx/2006/xaml/presentation/sdk""
    mc:Ignorable=""d""
    d:DesignHeight=""300"" d:DesignWidth=""400"">
    <controls:CustomTabControl >
        <sdk:TabItem Header=""{Binding Path=Title}"">
            <views:DataContentPresenter Content=""{Binding Path=ViewModel}"" Refresh=""True"" CanUnload=""True""/>
        </sdk:TabItem>
    </controls:CustomTabControl>
</views:UserView>")]
        public string DefaultDetailViewXaml {
            get {
                return ((string)(this["DefaultDetailViewXaml"]));
            }
            set {
                this["DefaultDetailViewXaml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<views:UserView x:Class=\"%namespace%.%classname%MasterView\"\r\n    xmlns=\"http://sc" +
            "hemas.microsoft.com/winfx/2006/xaml/presentation\"\r\n    xmlns:x=\"http://schemas.m" +
            "icrosoft.com/winfx/2006/xaml\"\r\n    xmlns:d=\"http://schemas.microsoft.com/express" +
            "ion/blend/2008\"\r\n    xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatib" +
            "ility/2006\"\r\n    xmlns:views=\"clr-namespace:DatumNode.Views;assembly=DatumNode.C" +
            "ontrols\"\r\n    xmlns:sdk=\"http://schemas.microsoft.com/winfx/2006/xaml/presentati" +
            "on/sdk\"\r\n    xmlns:controls=\"clr-namespace:Oss.Controls\"\r\n    mc:Ignorable=\"d\"\r\n" +
            "    d:DesignHeight=\"300\" d:DesignWidth=\"745\">\r\n    <Grid x:Name=\"LayoutRoot\">\r\n " +
            "       <Grid.ColumnDefinitions>\r\n            <ColumnDefinition Width=\"1*\"/>\r\n   " +
            "         <ColumnDefinition Width=\"auto\"/>\r\n            <ColumnDefinition Width=\"" +
            "2*\"/>\r\n        </Grid.ColumnDefinitions>\r\n        <views:DataContentPresenter x:" +
            "Name=\"Master\" Content=\"{Binding Path=MasterViewModel}\"/>\r\n        <sdk:GridSplit" +
            "ter Grid.Column=\"1\" VerticalAlignment=\"Stretch\" HorizontalAlignment=\"Center\" Vis" +
            "ibility=\"{Binding ElementName=CheckBox, Path=IsChecked, Converter={StaticResourc" +
            "e BooleanToVisibilityConverter}}\" />\r\n        <Grid Grid.Row=\"0\" Grid.Column=\"2\"" +
            ">\r\n            <Grid.RowDefinitions>\r\n                <RowDefinition Height=\"Aut" +
            "o\"/>\r\n                <RowDefinition/>\r\n            </Grid.RowDefinitions>\r\n    " +
            "        <controls:CustomCheckBox Grid.Row=\"0\" Grid.Column=\"0\" Target=\"{Binding E" +
            "lementName=Master}\" x:Name=\"CheckBox\" Content=\"{Binding Path=MasterViewModel.Cur" +
            "rentItem}\" IsChecked=\"True\" Visibility=\"{Binding Path=CurrentItem, Converter={St" +
            "aticResource NullToVisibilityConverter}}\"/>\r\n            <views:DataContentPrese" +
            "nter Grid.Row=\"1\" Grid.Column=\"0\" x:Name=\"Detail\" Content=\"{Binding Path=DetailV" +
            "iewModel}\"/>\r\n        </Grid>\r\n    </Grid>\r\n</views:UserView>  ")]
        public string DefaultMasterViewXaml {
            get {
                return ((string)(this["DefaultMasterViewXaml"]));
            }
            set {
                this["DefaultMasterViewXaml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public partial class %classname%MasterView\r\n    {\r\n" +
            "    \tpublic %classname%MasterView()\r\n    \t{\r\n    \t\tInitializeComponent();\r\n    \t" +
            "}\r\n    }\r\n}")]
        public string DefaultMasterView {
            get {
                return ((string)(this["DefaultMasterView"]));
            }
            set {
                this["DefaultMasterView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("namespace %namespace%\r\n{\r\n    public partial class %classname%DetailView\r\n    {\r\n" +
            "    \tpublic %classname%DetailView()\r\n    \t{\r\n    \t\tInitializeComponent();\r\n    \t" +
            "}\r\n    }\r\n}")]
        public string DefaultDetailView {
            get {
                return ((string)(this["DefaultDetailView"]));
            }
            set {
                this["DefaultDetailView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DetailViewFolder {
            get {
                return ((string)(this["DetailViewFolder"]));
            }
            set {
                this["DetailViewFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DetailViewModelFolder {
            get {
                return ((string)(this["DetailViewModelFolder"]));
            }
            set {
                this["DetailViewModelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterViewFolder {
            get {
                return ((string)(this["MasterViewFolder"]));
            }
            set {
                this["MasterViewFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MasterViewModelFolder {
            get {
                return ((string)(this["MasterViewModelFolder"]));
            }
            set {
                this["MasterViewModelFolder"] = value;
            }
        }
    }
}
